env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: 'typescript-eslint-parser'
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  no-undef: off
  no-dupe-class-members: off
  no-unused-vars: off
  indent:
    - error
    - tab
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-var:
    - error
